### ISSUE TITLE
Add HACS version

### ISSUE THREAD

**Issue by ScottG489** [jariz/homeassistant-basestation#6]
Right now the version for this integration is being reported as the git commit hash. We should have a HACS version added for clarity.

I believe all that's necessary is to have a [manifest.json](https://hacs.xyz/docs/publish/integration/#manifestjson) file. Specifically `custom_components/basestation/manifest.json` is what we'd want to create. In those linked docs it looks like we should have a few other keys defined as well.

I can create a PR for this. Any preference on a starting version?

**Comment by ScottG489** [comment]
Seems I spoke too soon. It looks like we already have a `manifest.json`. The only reason I can think of then is that we need to create a [release](https://docs.github.com/en/repositories/releasing-projects-on-github) in GitHub.

**Comment by ScottG489** [comment]
After having published my own HACS project, I can confirm that not having a release is indeed the reason there's no version in HACS.

**Comment by nikolaychernev** [comment]
I just added a v1.0.0 tag and the first release

**Comment by ScottG489** [comment]
Thanks!
